# Generated by Django 4.2.30 on 2026-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('TRUCK_NEAR', 'Truck Near'), ('COLLECTION_DONE', 'Collection Done'), ('DUMPSITE_INBOUND', 'Dumpsite Inbound')], default='ANNOUNCEMENT', max_length=20),
        ),
    ]
