# Generated by Django 4.2.30 on 2026-06-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('TRUCK_NEAR', 'Truck Near'), ('COLLECTION_DONE', 'Collection Done'), ('DUMPSITE_INBOUND', 'Dumpsite Inbound'), ('WATCHER_STOP_VERIFIED', 'Watcher Stop Verified'), ('WATCHER_ROUTE_SUMMARY', 'Watcher Route Summary')], default='ANNOUNCEMENT', max_length=50),
        ),
    ]
