# Generated by Django 4.2.30 on 2026-06-16 03:19

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0016_remove_dumpsite_barangay_remove_dumpsite_operator_and_more'),
        ('accounts', '0009_remove_barangay_clinics_remove_barangay_hospitals_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("ALTER TABLE driver_dumpsite RENAME TO dumpsite_dumpsite;"),
                migrations.RunSQL("ALTER TABLE driver_wastedelivery RENAME TO dumpsite_wastedelivery;"),
                migrations.RunSQL("ALTER TABLE driver_dumpsiteincident RENAME TO dumpsite_dumpsiteincident;"),
                migrations.RunSQL("ALTER TABLE driver_truckfillestimate RENAME TO dumpsite_truckfillestimate;"),
            ],
            state_operations=[
                migrations.CreateModel(
            name='Dumpsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('landfill', 'Landfill'), ('dumpsite', 'Open Dumpsite'), ('transfer', 'Transfer Station'), ('composting', 'Composting Area')], default='dumpsite', max_length=20)),
                ('capacity_used', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_capacity_kg', models.DecimalField(decimal_places=2, default=50000.0, help_text='Total site capacity in kg.', max_digits=10)),
                ('current_fill_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Running total of KG received. Incremented on each log_arrival POST.', max_digits=10)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumpsites', to='accounts.barangay')),
                ('operator', models.OneToOneField(blank=True, help_text='The linked dumpsite operator account.', limit_choices_to={'role': 'dumpsite'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_dumpsite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('estimated_kg', models.DecimalField(decimal_places=2, default=0, help_text='Operator-estimated KG from fill level slider.', max_digits=10)),
                ('fill_level', models.CharField(blank=True, choices=[('nearly_empty', 'Nearly Empty (0–25%)'), ('quarter', 'Quarter (26–50%)'), ('half', 'Half (51–75%)'), ('three_quarters', 'Three Quarters (76–99%)'), ('full', 'Full (100%)'), ('overflowing', 'Overflowing (100%+)')], max_length=20)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='arrival proof')),
                ('remarks', models.TextField(blank=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Dumpsite operator confirmed this record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_deliveries', to='accounts.barangay')),
                ('crew_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='driver.truckcrewassignment')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_as_driver', to=settings.AUTH_USER_MODEL)),
                ('dumpsite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='dumpsite.dumpsite')),
                ('dumpsite_operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'dumpsite'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_received', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='driver.collectionschedule')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='driver.truck')),
            ],
            options={
                'verbose_name': 'Waste Delivery',
                'verbose_name_plural': 'Waste Deliveries',
                'ordering': ['-date', '-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='DumpsiteIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('contaminated_load', 'Contaminated Load'), ('wrong_barangay', 'Wrong Barangay'), ('missing_crew', 'Missing Crew'), ('weight_discrepancy', 'Weight Discrepancy'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='dumpsite.wastedelivery')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TruckFillEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.CharField(choices=[('nearly_empty', 'Nearly Empty'), ('quarter', 'Quarter'), ('half', 'Half'), ('three_quarters', 'Three Quarters'), ('full', 'Full'), ('overflowing', 'Overflowing')], max_length=20)),
                ('estimated_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_custom', models.BooleanField(default=False, help_text='If True, admin manually set this value — skip auto-recalculation.')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_estimates', to='driver.truck')),
            ],
            options={
                'ordering': ['truck', 'fill_level'],
                'unique_together': {('truck', 'fill_level')},
            },
        ),
    ]
            )
        ]
