# Generated by Django 4.2.30 on 2026-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_dumpsite'),
        ('dumpsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastedelivery',
            name='barangay',
        ),
        migrations.AddField(
            model_name='wastedelivery',
            name='barangays',
            field=models.ManyToManyField(blank=True, related_name='waste_deliveries', to='accounts.barangay'),
        ),
    ]
