# Generated by Django 4.2.30 on 2026-06-22 22:38
# Adds DB-level indexes on WasteDelivery used by /api/analytics/live/

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpsite', '0002_remove_wastedelivery_barangay_and_more'),
    ]

    operations = [
        # Hot path: date-range filter for daily time-series aggregation
        migrations.AddIndex(
            model_name='wastedelivery',
            index=models.Index(fields=['date'], name='wastedlvry_date_idx'),
        ),
        # Hot path: per-truck delivery aggregation
        migrations.AddIndex(
            model_name='wastedelivery',
            index=models.Index(fields=['truck', 'date'], name='wastedlvry_truck_date_idx'),
        ),
    ]
