# Generated by Django 4.2.30 on 2026-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumpsite', '0003_add_analytics_indexes_wastedelivery'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wastedelivery',
            name='wastedlvry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='wastedelivery',
            name='wastedlvry_truck_date_idx',
        ),
    ]
