# Generated by Django 6.0.4 on 2026-05-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('announcement', 'Announcement'), ('news', 'News'), ('emergency', 'Emergency')], default='news', max_length=20)),
                ('category', models.CharField(choices=[('Announcements', 'Announcements'), ('News', 'News'), ('Cleanup Drives', 'Cleanup Drives'), ('Rankings', 'Rankings'), ('Advisories', 'Advisories'), ('Emergencies', 'Emergencies')], default='News', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('barangay', models.CharField(default='City-Wide', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('accent_color', models.CharField(blank=True, help_text='HEX color, e.g., #e74c3c', max_length=7)),
                ('bg_color', models.CharField(blank=True, help_text='HEX color, e.g., #7f1d1d', max_length=7)),
            ],
            options={
                'ordering': ['-is_pinned', '-date'],
            },
        ),
        migrations.CreateModel(
            name='BarangaySpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('improvement', models.CharField(max_length=10)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=10)),
                ('icon', models.CharField(default='award', max_length=50)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay')),
            ],
        ),
    ]
