# Generated by Django 4.2.30 on 2026-06-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_employee_type_alter_user_role'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Leave null for city-wide announcements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='accounts.barangay'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
