# Generated by Django 4.2.30 on 2026-06-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsitem_barangay_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image shown on dashboards and the news feed.', null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Announcements', 'Announcements'), ('News', 'News'), ('Service Updates', 'Service Updates'), ('Community', 'Community'), ('Cleanup Drives', 'Cleanup Drives'), ('Rankings', 'Rankings'), ('Advisories', 'Advisories'), ('Emergency', 'Emergency'), ('Emergencies', 'Emergencies')], default='News', max_length=30),
        ),
    ]
