# Generated by Django 4.2.30 on 2026-06-17 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsitem_image_and_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image shown on dashboards and the news feed.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
