# Generated by Django 6.0.4 on 2026-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='cleanliness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='households',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='zone_type',
            field=models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural'), ('coastal', 'Coastal'), ('mixed', 'Mixed')], default='urban', max_length=20),
        ),
    ]
