# Generated by Django 6.0.4 on 2026-05-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_barangay_cleanliness_score_barangay_households_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='cleanliness_score',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='households',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='population',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='zone_type',
        ),
    ]
