# Generated by Django 6.0.4 on 2026-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_barangay_cleanliness_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('brgy_official', 'Brgy Official'), ('watcher', 'Watcher'), ('driver', 'Driver'), ('citizen', 'Citizen'), ('dumpsite', 'Dumpsite')], default='citizen', max_length=20),
        ),
    ]
