# Generated by Django 6.0.4 on 2026-06-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dumpsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='driver.dumpsite'),
        ),
    ]
