# Generated by Django 4.2.30 on 2026-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_dumpsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('crew_member', 'Crew Member')], default='', help_text="Set to 'crew_member' for citizens who serve on collection trucks.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('brgy_official', 'Brgy Official'), ('watcher', 'Watcher'), ('driver', 'Driver'), ('citizen', 'Citizen'), ('dumpsite', 'Dumpsite Operator')], default='citizen', max_length=20),
        ),
    ]
