# Generated by Django 4.2.30 on 2026-06-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_employee_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='profiles/'),
        ),
    ]
