# Generated by Django 4.2.30 on 2026-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='clinics',
            field=models.PositiveIntegerField(default=0, help_text='Number of clinics in the barangay'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='hospitals',
            field=models.PositiveIntegerField(default=0, help_text='Number of hospitals in the barangay'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='population',
            field=models.PositiveIntegerField(default=0, help_text='Total population of the barangay'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='schools',
            field=models.PositiveIntegerField(default=0, help_text='Number of schools in the barangay'),
        ),
    ]
