# Generated by Django 4.2.30 on 2026-06-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_barangay_clinics_barangay_hospitals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='clinics',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='schools',
        ),
        migrations.AlterField(
            model_name='barangay',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BarangayEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of establishment, e.g. Hospital, School, Store', max_length=100)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of this establishment type in the barangay')),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='accounts.barangay')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
                'ordering': ['name'],
                'unique_together': {('barangay', 'name')},
            },
        ),
    ]
