# Generated by Django 4.2.30 on 2026-06-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumpsite', '0001_initial'),
        ('accounts', '0009_remove_barangay_clinics_remove_barangay_hospitals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dumpsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='dumpsite.dumpsite'),
        ),
    ]
