# Generated by Django 4.2.30 on 2026-06-17 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_dumpsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="User's profile picture.", max_length=255, null=True, verbose_name='image'),
        ),
    ]
