# Generated by Django 4.2.30 on 2026-06-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='GeoJSON representation of the barangay boundary', null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
