# Generated by Django 4.2.30 on 2026-06-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_user_employee_type_alter_user_role'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='False = historical record')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('crew_members', models.ManyToManyField(blank=True, limit_choices_to={'employee_type': 'crew_member'}, related_name='crew_assignments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_assignments', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_assignments', to='driver.collectionschedule')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='driver.truck')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WasteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Dumpsite operator confirmed this record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_deliveries', to='accounts.barangay')),
                ('crew_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='driver.truckcrewassignment')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_as_driver', to=settings.AUTH_USER_MODEL)),
                ('dumpsite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='driver.dumpsite')),
                ('dumpsite_operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'dumpsite'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_received', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='driver.collectionschedule')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='driver.truck')),
            ],
            options={
                'verbose_name': 'Waste Delivery',
                'verbose_name_plural': 'Waste Deliveries',
                'ordering': ['-date', '-arrival_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='truckcrewassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('truck', 'date', 'schedule'), name='unique_active_assignment_per_truck_date_schedule'),
        ),
    ]
