# Generated by Django 4.2.30 on 2026-06-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_truckcrewassignment_wastedelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionschedule',
            name='dumpsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_schedules', to='driver.dumpsite'),
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='waypoints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
