# Generated by Django 4.2.30 on 2026-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_employee_type_alter_user_role'),
        ('driver', '0003_collectionschedule_dumpsite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionschedule',
            name='barangay',
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='barangays',
            field=models.ManyToManyField(blank=True, related_name='collection_schedules', to='accounts.barangay'),
        ),
    ]
