# Generated by Django 4.2.30 on 2026-06-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0005_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(default='normal', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='driver.truck')),
            ],
        ),
        migrations.AddConstraint(
            model_name='drivershift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('driver',), name='unique_active_shift_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='drivershift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('truck',), name='unique_active_shift_per_truck'),
        ),
    ]
