# Generated by Django 4.2.30 on 2026-06-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_drivershift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='driver.drivershift'),
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='driver.truck'),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
