# Generated by Django 4.2.30 on 2026-06-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_drivershift_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='op_status',
            field=models.CharField(default='on_duty', help_text='Operational status: on_duty | on_route | delayed', max_length=20),
        ),
    ]
