# Generated by Django 4.2.30 on 2026-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_add_op_status_to_drivershift'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drivershift',
            index=models.Index(fields=['is_active'], name='drivershift_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='drivershift',
            index=models.Index(fields=['driver', '-started_at'], name='drivershift_driver_started_idx'),
        ),
        migrations.AddIndex(
            model_name='trucklocation',
            index=models.Index(fields=['shift', '-timestamp'], name='truckloc_shift_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='trucklocation',
            index=models.Index(fields=['driver', '-timestamp'], name='truckloc_driver_ts_idx'),
        ),
    ]
