# Generated by Django 4.2.30 on 2026-06-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupstatus',
            options={'ordering': ['stop_order']},
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='collected_at',
            field=models.DateTimeField(blank=True, help_text='When the driver marked this stop collected', null=True),
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='stop_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this stop in the route'),
        ),
    ]
