# Generated by Django 4.2.30 on 2026-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_pickup_status_stop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklocation',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy radius in metres', max_digits=8, null=True),
        ),
    ]
