# Generated by Django 4.2.30 on 2026-06-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_alter_pickupstatus_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverNotification',
        ),
    ]
