# Generated by Django 4.2.30 on 2026-06-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_pic'),
        ('driver', '0013_delete_drivernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupstatus',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='accounts.barangay'),
        ),
        migrations.AddField(
            model_name='pickupstatus',
            name='stop_id',
            field=models.CharField(blank=True, help_text='Stable stop ID from route builder', max_length=100, null=True),
        ),
    ]
