# Generated by Django 4.2.30 on 2026-06-15 14:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0014_pickupstatus_barangay_pickupstatus_stop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpsite',
            name='current_fill_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Running total of KG received. Incremented on each log_arrival POST.', max_digits=10),
        ),
        migrations.AddField(
            model_name='dumpsite',
            name='max_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Total site capacity in kg.', max_digits=10),
        ),
        migrations.AddField(
            model_name='dumpsite',
            name='operator',
            field=models.OneToOneField(blank=True, help_text='The linked dumpsite operator account.', limit_choices_to={'role': 'dumpsite'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_dumpsite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='truck',
            name='max_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Rated maximum payload in kg. Used by dumpsite fill slider.', max_digits=8),
        ),
        migrations.AddField(
            model_name='wastedelivery',
            name='estimated_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Operator-estimated KG from fill level slider.', max_digits=10),
        ),
        migrations.AddField(
            model_name='wastedelivery',
            name='fill_level',
            field=models.CharField(blank=True, choices=[('nearly_empty', 'Nearly Empty (0–25%)'), ('quarter', 'Quarter (26–50%)'), ('half', 'Half (51–75%)'), ('three_quarters', 'Three Quarters (76–99%)'), ('full', 'Full (100%)'), ('overflowing', 'Overflowing (100%+)')], max_length=20),
        ),
        migrations.AddField(
            model_name='wastedelivery',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='arrival proof'),
        ),
        migrations.AlterField(
            model_name='wastedelivery',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DumpsiteIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('contaminated_load', 'Contaminated Load'), ('wrong_barangay', 'Wrong Barangay'), ('missing_crew', 'Missing Crew'), ('weight_discrepancy', 'Weight Discrepancy'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='driver.wastedelivery')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TruckFillEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.CharField(choices=[('nearly_empty', 'Nearly Empty'), ('quarter', 'Quarter'), ('half', 'Half'), ('three_quarters', 'Three Quarters'), ('full', 'Full'), ('overflowing', 'Overflowing')], max_length=20)),
                ('estimated_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_custom', models.BooleanField(default=False, help_text='If True, admin manually set this value — skip auto-recalculation.')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_estimates', to='driver.truck')),
            ],
            options={
                'ordering': ['truck', 'fill_level'],
                'unique_together': {('truck', 'fill_level')},
            },
        ),
    ]
