# Generated by Django 4.2.30 on 2026-06-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_dumpsite_current_fill_kg_dumpsite_max_capacity_kg_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='dumpsite',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='dumpsite',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='dumpsiteincident',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='dumpsiteincident',
            name='reported_by',
        ),
        migrations.AlterUniqueTogether(
            name='truckfillestimate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='truckfillestimate',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='crew_assignment',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='dumpsite',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='dumpsite_operator',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='wastedelivery',
            name='truck',
        ),
        ]
        )
    ]
