# Generated by Django 4.2.30 on 2026-06-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_dumpsite'),
        ('driver', '0016_remove_dumpsite_barangay_remove_dumpsite_operator_and_more'),
        ('dumpsite', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
            model_name='collectionschedule',
            name='dumpsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_schedules', to='dumpsite.dumpsite'),
        ),
        migrations.DeleteModel(
            name='Dumpsite',
        ),
        migrations.DeleteModel(
            name='DumpsiteIncident',
        ),
        migrations.DeleteModel(
            name='TruckFillEstimate',
        ),
        migrations.DeleteModel(
            name='WasteDelivery',
        ),
        ]
        )
    ]
