# Generated by Django 4.2.30 on 2026-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_alter_collectionschedule_dumpsite_delete_dumpsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupstatus',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='pickup-proofs/'),
        ),
    ]
