# Generated by Django 4.2.30 on 2026-06-17 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_alter_pickupstatus_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupstatus',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
