# Generated by Django 4.2.30 on 2026-06-17 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0019_alter_pickupstatus_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
