# Generated by Django 4.2.30 on 2026-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_truck_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='maintenance_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
