# Generated by Django 4.2.30 on 2026-06-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0021_truck_maintenance_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for maintenance or inactive status', null=True),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
