# Generated by Django 4.2.30 on 2026-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0022_truck_status_reason_alter_collectionschedule_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='past_crew_names',
            field=models.TextField(blank=True, help_text='Stores the names of the last assigned crew when the truck becomes inactive.', null=True),
        ),
    ]
