# Generated by Django 4.2.30 on 2026-06-17 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0023_truck_past_crew_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='assigned_trucks', to=settings.AUTH_USER_MODEL),
        ),
    ]
