# Generated by Django 4.2.30 on 2026-06-17 17:37

from django.db import migrations


def migrate_drivers(apps, schema_editor):
    Truck = apps.get_model('driver', 'Truck')
    for truck in Truck.objects.all():
        if truck.driver_id:
            truck.drivers.add(truck.driver_id)

def unmigrate_drivers(apps, schema_editor):
    Truck = apps.get_model('driver', 'Truck')
    for truck in Truck.objects.all():
        if truck.drivers.exists():
            truck.driver = truck.drivers.first()
            truck.save()

class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0024_truck_drivers'),
    ]

    operations = [
        migrations.RunPython(migrate_drivers, unmigrate_drivers),
    ]
