# Generated by Django 4.2.30 on 2026-06-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0025_migrate_truck_driver_to_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
    ]
