# Generated by Django 4.2.30 on 2026-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0026_remove_truck_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='status',
            field=models.CharField(choices=[('navigate_to_base', 'Navigating to base'), ('confirm_start', 'Confirming start'), ('checkin', 'Check-in'), ('shiftroute', 'On route'), ('end_shift', 'Ending shift')], default='navigate_to_base', max_length=32),
        ),
    ]
