# Generated by Django 4.2.30 on 2026-06-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0027_drivershift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='is_extended_mode',
            field=models.BooleanField(default=False, help_text='True if driver opted to take missed stops'),
        ),
        migrations.AlterField(
            model_name='drivershift',
            name='op_status',
            field=models.CharField(default='on_duty', help_text='Operational status: on_duty | on_route | heading_to_dumpsite | at_dumpsite | returning_to_base | delayed', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickupstatus',
            name='status',
            field=models.CharField(choices=[('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DRIVER_MISSED', 'Driver Missed')], default='EN_ROUTE', max_length=20),
        ),
    ]
