# Generated by Django 4.2.30 on 2026-06-22 21:14
# Adds DB-level indexes on PickupStatus used by /api/analytics/live/

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0028_drivershift_is_extended_mode_and_more'),
    ]

    operations = [
        # Hot path: filter PickupStatus by status ('COMPLETED', 'DRIVER_MISSED', etc.)
        migrations.AddIndex(
            model_name='pickupstatus',
            index=models.Index(fields=['status'], name='pickupstatus_status_idx'),
        ),
        # Hot path: per-barangay completion aggregation
        migrations.AddIndex(
            model_name='pickupstatus',
            index=models.Index(fields=['barangay', 'status'], name='pickupstatus_brgy_status_idx'),
        ),
        # Hot path: date-range filter via schedule__date
        migrations.AddIndex(
            model_name='pickupstatus',
            index=models.Index(fields=['schedule'], name='pickupstatus_schedule_idx'),
        ),
    ]
