# Generated by Django 4.2.30 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0029_add_analytics_indexes_pickupstatus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pickupstatus',
            name='pickupstatus_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='pickupstatus',
            name='pickupstatus_brgy_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='pickupstatus',
            name='pickupstatus_schedule_idx',
        ),
        migrations.AddField(
            model_name='drivershift',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='The specific route/schedule this shift is executing. Set at shift-start time so schedule_id is authoritative, not re-derived on every request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_shifts', to='driver.collectionschedule'),
        ),
    ]
