# Generated by Django 4.2.30 on 2026-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0030_remove_pickupstatus_pickupstatus_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='end_shift_phase',
            field=models.CharField(blank=True, default='', help_text='EndShiftModule sub-phase: dump_site | waiting_dump_confirmation | returning | at_base | calibration_complete', max_length=40),
        ),
    ]
