# Generated by Django 4.2.30 on 2026-07-09 02:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0031_add_end_shift_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
