# Generated by Django 4.2.30 on 2026-09-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0019_stopvalidation_driver_bypassed_watcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0032_truck_date_bought_truck_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('waypoint_data', models.JSONField(help_text='Stores lat, lng, label, barangay_id, stop_id')),
                ('reason', models.CharField(choices=[('TRUCK_FULL', 'Truck was full'), ('EXPIRED_TIME', 'Time expired without visit'), ('WATCHER_FLAG', 'Falsely reported collected (Watcher flagged)'), ('DRIVER_SKIP', 'Driver intentionally skipped'), ('SHIFT_ENDED_EARLY', 'Shift ended early (Breakdown, weather, etc)')], max_length=20)),
                ('early_end_reason', models.CharField(blank=True, help_text='Specific reason if SHIFT_ENDED_EARLY', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending reassignment'), ('RESOLVED', 'Collected by extended driver'), ('EXPIRED', 'Not collected (day ended)')], default='PENDING', max_length=15)),
                ('collection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_stops', to='watcher.escalation')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_stops', to='driver.collectionschedule')),
                ('resolved_by_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_missed_stops', to='driver.drivershift')),
            ],
            options={
                'ordering': ['collection_date', 'original_schedule', 'stop_order'],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('missed_stops_recovered', models.IntegerField(default=0)),
                ('missed_stops_caused', models.IntegerField(default=0, help_text='Increments only for penalized reasons (e.g. WATCHER_FLAG, DRIVER_SKIP)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='missedstop',
            constraint=models.UniqueConstraint(fields=('original_schedule', 'stop_order', 'collection_date'), name='unique_missed_stop'),
        ),
    ]
