# Generated by Django 6.0.4 on 2026-05-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SystemKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('This Week', 'This Week'), ('Last Week', 'Last Week'), ('This Month', 'This Month'), ('Last Month', 'Last Month')], max_length=20)),
                ('collected_kg', models.IntegerField(default=0)),
                ('total_routes', models.IntegerField(default=0)),
                ('completed_routes', models.IntegerField(default=0)),
                ('missed_stops', models.IntegerField(default=0)),
                ('avg_fill_rate', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System KPI',
                'verbose_name_plural': 'System KPIs',
            },
        ),
        migrations.CreateModel(
            name='TruckPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('This Week', 'This Week'), ('Last Week', 'Last Week'), ('This Month', 'This Month'), ('Last Month', 'Last Month')], max_length=20)),
                ('routes', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('missed', models.IntegerField(default=0)),
                ('avg_fill', models.IntegerField(default=0)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BarangayPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('This Week', 'This Week'), ('Last Week', 'Last Week'), ('This Month', 'This Month'), ('Last Month', 'Last Month')], max_length=20)),
                ('reports', models.IntegerField(default=0)),
                ('resolved', models.IntegerField(default=0)),
                ('waste_collected_kg', models.IntegerField(default=0)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay')),
            ],
        ),
    ]
