# Generated by Django 6.0.4 on 2026-06-03 15:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_garbagehotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagereport',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
