# Generated by Django 6.0.6 on 2026-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_garbagereport_address_alter_garbagereport_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
