# Generated by Django 4.2.30 on 2026-06-08 18:19

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_alter_pickupstatus_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watcher', '0008_garbagereport_approved_at_garbagereport_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Waypoint index (1 = first collection stop)')),
                ('collection_date', models.DateField(help_text='The scheduled collection day for this validation cycle')),
                ('current_status', models.CharField(choices=[('PENDING_INSPECTION', 'Pending Inspection'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('EMPTY_STOP', 'Empty Stop'), ('COLLECTION_REPORTED', 'Collection Reported'), ('VERIFIED_COLLECTED', 'Verified Collected'), ('COLLECTION_DISPUTED', 'Collection Disputed')], default='PENDING_INSPECTION', max_length=30)),
                ('pre_validation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pre_validation_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pre validation proof')),
                ('pre_validation_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pre_validation_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pre_validation_remarks', models.TextField(blank=True)),
                ('collection_timestamp', models.DateTimeField(blank=True, null=True)),
                ('collection_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='collection proof')),
                ('collection_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('collection_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('collection_notes', models.TextField(blank=True)),
                ('post_validation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('post_validation_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post validation proof')),
                ('post_validation_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('post_validation_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_stop_collections', to=settings.AUTH_USER_MODEL)),
                ('post_validation_watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_validations', to=settings.AUTH_USER_MODEL)),
                ('pre_validation_watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_validations', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_validations', to='driver.collectionschedule')),
            ],
            options={
                'ordering': ['collection_date', 'schedule_id', 'stop_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='stopvalidation',
            constraint=models.UniqueConstraint(fields=('schedule', 'stop_order', 'collection_date'), name='unique_stop_validation_per_day'),
        ),
    ]
