# Generated by Django 4.2.30 on 2026-06-10 19:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0009_stop_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopvalidation',
            name='post_validation_photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post validation proof 2'),
        ),
        migrations.AddField(
            model_name='stopvalidation',
            name='post_validation_photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post validation proof 3'),
        ),
        migrations.AddField(
            model_name='stopvalidation',
            name='post_validation_photo_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post validation proof 4'),
        ),
        migrations.AddField(
            model_name='stopvalidation',
            name='pre_validation_photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pre validation proof 2'),
        ),
        migrations.AddField(
            model_name='stopvalidation',
            name='pre_validation_photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pre validation proof 3'),
        ),
        migrations.AddField(
            model_name='stopvalidation',
            name='pre_validation_photo_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pre validation proof 4'),
        ),
    ]
