# Generated by Django 4.2.30 on 2026-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_stopvalidation_barangay_stopvalidation_stop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='collection_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stop-collection/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='post_validation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stop-post-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='post_validation_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='stop-post-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='post_validation_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='stop-post-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='post_validation_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='stop-post-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='pre_validation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stop-pre-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='pre_validation_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='stop-pre-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='pre_validation_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='stop-pre-validation/'),
        ),
        migrations.AlterField(
            model_name='stopvalidation',
            name='pre_validation_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='stop-pre-validation/'),
        ),
    ]
