# Generated by Django 6.0.6 on 2026-06-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='reported_user',
            field=models.ForeignKey(blank=True, help_text='The person (driver/watcher) being reported for misconduct', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_misconduct_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
