# Generated by Django 4.2.30 on 2026-06-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0012_garbagereport_reported_user'),
        ('watcher', '0013_alter_stopvalidation_collection_photo_and_more'),
    ]

    operations = [
    ]
