# Generated by Django 4.2.30 on 2026-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0014_merge_20260619_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopvalidation',
            name='current_status',
            field=models.CharField(choices=[('PENDING_INSPECTION', 'Pending Inspection'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('EMPTY_STOP', 'Empty Stop'), ('COLLECTION_REPORTED', 'Collection Reported'), ('VERIFIED_COLLECTED', 'Verified Collected'), ('COLLECTION_DISPUTED', 'Missed')], default='PENDING_INSPECTION', max_length=30),
        ),
    ]
