# Generated by Django 4.2.30 on 2026-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0015_alter_stopvalidation_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
