# Generated by Django 4.2.30 on 2026-07-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0032_truck_date_bought_truck_photo'),
        ('watcher', '0016_garbagereport_image_2_garbagereport_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagehotspot',
            name='assigned_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hotspots', to='driver.truck'),
        ),
    ]
