# Generated by Django 4.2.30 on 2026-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0018_garbagehotspot_source_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopvalidation',
            name='driver_bypassed_watcher',
            field=models.BooleanField(default=False, help_text='True if the driver bypassed watcher pre-inspection (e.g. Watcher Delayed)'),
        ),
    ]
